# Generated by Django 5.2.16 on 2026-07-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
        ('transactions', '0003_transaction_request_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for manual fine', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='transactions.transaction'),
        ),
    ]
