# Generated by Django 5.2.16 on 2026-07-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_fine_reason_alter_fine_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], db_index=True, default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(choices=[('DIGITAL_WALLET', 'Digital Wallet'), ('CARD', 'Credit/Debit Card'), ('CASH', 'Cash at Desk'), ('MANUAL_BANK_TRANSFER', 'Manual Bank Transfer')], default='DIGITAL_WALLET', max_length=30),
        ),
    ]
