# Generated by Django 5.2.16 on 2026-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_gateaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='request_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING_EXTENSION', 'Pending Extension'), ('PENDING_RETURN', 'Pending Return'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=30),
        ),
    ]
