# Generated by Django 5.2.16 on 2026-07-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('LIBRARIAN', 'Librarian'), ('ADMIN', 'Administrator')], max_length=20, unique=True)),
                ('max_borrow_limit', models.IntegerField(default=3)),
                ('default_loan_days', models.IntegerField(default=14)),
                ('fine_rate_per_day', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('grace_period_days', models.IntegerField(default=2)),
                ('reservation_hold_hours', models.IntegerField(default=48)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
