# Generated by Django 5.2.16 on 2026-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionpolicy',
            name='max_renewals_allowed',
            field=models.IntegerField(default=2),
        ),
    ]
